services:
  db:
    image: postgres
    environment: 
      POSTGRES_PASSWORD: 'password'
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
  
  mailcatcher:
    image: schickling/mailcatcher
    ports:
      - '1080:1080'
      - '1025:1025'

volumes:
  pg_data:
